### ISSUE TITLE
A Lib não tem compatibilidade com V5 da api Pagarme

### ISSUE THREAD

**Issue by heltonteixeira92** [renzon/django_pagarme#172]
Atualmente ao se cadastrar no pagarme, só temos disponibilidade para acessar a V5 (dashboard 2.0) da API do pagarme e suas devidas keys, porem isso pode ser resolvido enquanto a Lib não é atualizada.
Entre em contato com o suporte do pagarme e peça migração para o dashboard 1.0, e você terá disponibilidade de acessar as versões V4, V3, V2 e V1 da API.

**Comment by renzon** [comment]
Vamos ver como migrar para a nova API.
