### ISSUE TITLE
Adicionar CI

### ISSUE THREAD

**Issue by rafaelhfreitas** [renzon/django_pagarme#5]

**Comment by rafaelhfreitas** [comment]
Apenas a título de curiosidade, eu ia colocar os escudos/distintivos no readme, tipo o escudo do travis que indica se houve o build ou não, mais ai como o repo é um fork, o distintivo iria apontar para o meu repo, ai seria melhor vc colocar no projeto ?

**Comment by renzon** [comment]
Exato Rafael, a parte do setup do Travis infelizmente só eu posso fazer. Mas estou querendo testar o CI do próprio GH para ver como é, possivelmente vai ser melhor não ter que fazer nenhuma configuração extra

**Comment by renzon** [comment]
Alterei a descrição para testar o CI do Próprio GH
