### ISSUE TITLE
Checkout will work on JS when there is only logged user data.

### ISSUE THREAD

**Issue by renzon** [renzon/django_pagarme#89]

**Comment by renzon** [comment]
To reproduce: log in, access /checkout/pagarme/pytools?open_modal=true

![Screen Shot 2020-03-18 at 7 52 10 AM](https://user-images.githubusercontent.com/3457115/76953491-8b30f200-68ed-11ea-9309-cf1f98535e95.png)

**Comment by engnogueira** [comment]
I've tried the two-income way and neither got worked
